In [1]:
import numpy as np

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5310, 1274, 2775, 4084],
 [5310, 1274, 2775, 1733],
 [5310, 8307, 2775, 5490],
 [5659, 9524, 69, 4970, 9218],
 [5659, 9524, 69, 4970, 6158],
 [6641, 5310, 6695, 2775, 3812],
 [9975, 3405, 7719, 4970]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5310 1274 2775 4084]
 [   0    0    0    0 5310 1274 2775 1733]
 [   0    0    0    0 5310 8307 2775 5490]
 [   0    0    0 5659 9524   69 4970 9218]
 [   0    0    0 5659 9524   69 4970 6158]
 [   0    0    0 6641 5310 6695 2775 3812]
 [   0    0    0    0 9975 3405 7719 4970]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\mohit\anaconda3\envs\genai-venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

None


In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step


array([[[ 0.02562093, -0.03642289,  0.03391639, -0.04950544,
         -0.0260681 ,  0.04993557,  0.04952171, -0.02274562,
         -0.02991935,  0.01331559],
        [ 0.02562093, -0.03642289,  0.03391639, -0.04950544,
         -0.0260681 ,  0.04993557,  0.04952171, -0.02274562,
         -0.02991935,  0.01331559],
        [ 0.02562093, -0.03642289,  0.03391639, -0.04950544,
         -0.0260681 ,  0.04993557,  0.04952171, -0.02274562,
         -0.02991935,  0.01331559],
        [ 0.02562093, -0.03642289,  0.03391639, -0.04950544,
         -0.0260681 ,  0.04993557,  0.04952171, -0.02274562,
         -0.02991935,  0.01331559],
        [-0.04795409, -0.0352472 ,  0.00668299, -0.01294856,
         -0.01752637, -0.03349924,  0.00077063, -0.01685675,
          0.00502973,  0.03532923],
        [-0.00901427,  0.01838083, -0.03515359, -0.03773862,
         -0.0176593 , -0.0326003 ,  0.02572589, -0.00431129,
          0.02838906, -0.03303834],
        [-0.00157464, -0.01987146, -0.02206194, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5310, 1274, 2775, 4084], dtype=int32)

In [16]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


array([[[ 0.02562093, -0.03642289,  0.03391639, -0.04950544,
         -0.0260681 ,  0.04993557,  0.04952171, -0.02274562,
         -0.02991935,  0.01331559],
        [ 0.02562093, -0.03642289,  0.03391639, -0.04950544,
         -0.0260681 ,  0.04993557,  0.04952171, -0.02274562,
         -0.02991935,  0.01331559],
        [ 0.02562093, -0.03642289,  0.03391639, -0.04950544,
         -0.0260681 ,  0.04993557,  0.04952171, -0.02274562,
         -0.02991935,  0.01331559],
        [ 0.02562093, -0.03642289,  0.03391639, -0.04950544,
         -0.0260681 ,  0.04993557,  0.04952171, -0.02274562,
         -0.02991935,  0.01331559],
        [-0.04795409, -0.0352472 ,  0.00668299, -0.01294856,
         -0.01752637, -0.03349924,  0.00077063, -0.01685675,
          0.00502973,  0.03532923],
        [-0.00901427,  0.01838083, -0.03515359, -0.03773862,
         -0.0176593 , -0.0326003 ,  0.02572589, -0.00431129,
          0.02838906, -0.03303834],
        [-0.00157464, -0.01987146, -0.02206194, -0.0